---
project: &project example_django_app
home: &home !path [ "~", *project ]
tmp: &tmp !path [ ~/.tmp ]

plugins:
  python:
    always: false
    venv: !path [ *home, venv ]
    packages: [ Django ]

jobs:
  up:
    help: Run [bold cyan]django/up[/] and open the front page.
    open: [ http://localhost:8000/ ]
    after: django/up

  down:
    help: Alias for [bold cyan]django/down[/].
    after: django/down

  shell:
    help: Open a shell with the Python virtual environment activated.
    run: !env ${SHELL}
    interactive: true
    silent: true
    after: plugin:python

  django/up:
    help: Start the Django web server.
    run: ./manage.py runserver &
    skip: !shell_eq_0 fuser -s 8000/tcp
    interactive: true
    sleep: 4
    after:
    - plugin:python
    - django/bootstrap
    - django/migrate

  django/shell:
    help: Start an interactive Django Python REPL.
    run: ./manage.py shell
    interactive: true
    silent: true
    after:
    - plugin:python
    - django/bootstrap
    - django/migrate

  django/down:
    help: Stop the Django web server.
    run: fuser -sk 8000/tcp
    skip: !shell_neq_0 fuser -s 8000/tcp

  django/migrate:
    help: Run Django database migrations
    run: ./manage.py migrate
    skip: !shell_eq_0 ./manage.py migrate --check
    after:
    - plugin:python
    - django/bootstrap

  django/bootstrap:
    help: Bootstrap the Django project.
    run: !cats [ django-admin startproject, *project, "." ]
    skip: !exists [ *home, manage.py ]
    after:
    - plugin:python

  django/destroy:
    help: Remove installation directory (you will be prompted first).
    run: !cats [ rm -rf, *home ]
    confirm: !cat [ "\n[bold yellow]:warning:[/]  Delete [bold cyan]", *home, "[/]?" ]
    skip: !not_exists [ *home ]
    after:
    - django/down

env:
  DISPLAY: !env ${DISPLAY}
  HOME: !env ${HOME}
  PATH: !env ${PATH}
  TERM: !env ${TERM}
  USER: !env ${USER}
  DJANGO_LOG_LEVEL: INFO
  DJANGO_SECRET_KEY: abc62himom9832qda
  DJANGO_SETTINGS_MODULE: !cat [ *project, .settings ]
